apiVersion: v1
kind: Service
metadata:
  name: traq-back-service
spec:
  selector:
    name: traq-frontend
    app: traq-back-demo-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110